config/routes.rb
Forgpresentation::Application.routes.draw do

  resources :discos

  resources :proyectos
  resources :fotos
  resources :videos
  
  match '/:id/fotos', :to => 'fotos#index', :as => 'index_fotos'
  match '/fotos/:id', :to => 'fotos#show', :as => 'show_foto'
  match '/fotos/:id/edit', :to => 'fotos#edit', :as => 'edit_foto'
  match '/fotos/:id/new', :to => 'fotos#new', :as => 'new_foto'  
  match '/videos/:id/new', :to => 'videos#new', :as => 'new_video'  
  match '/proyectos/:id/ver_proyecto', :to => 'proyectos#ver_proyecto', :as => 'ver_proyecto'
  match '/videos/:id/ver_video', :to => 'videos#ver_video', :as => 'ver_video'
  match '/fotos/:id/ver_galeria', :to => 'fotos#ver_galeria', :as => 'ver_galeria'
  match '/discos/:id/ver_catalogo', :to => 'discos#ver_catalogo', :as => 'ver_catalogo'
  match 'download' => 'proyectos#download';
	

  root :to => 'proyectos#index'

end

app/models/proyecto.rb
class Proyecto < ActiveRecord::Base
	validates :nombre, :presence => true
	
	has_many :fotos
	has_many :videos
end

app/controllers/proyectos_controller.rb
class ProyectosController < ApplicationController
  # GET /proyectos
  # GET /proyectos.json
	
	
  def index
    @proyectos = Proyecto.all
		#	@user_agent = request.env['HTTP_USER_AGENT']
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @proyectos }
    end
  end

  # GET /proyectos/1
  # GET /proyectos/1.json
  def show
    @proyecto = Proyecto.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @proyecto }
    end
  end

  # GET /proyectos/new
  # GET /proyectos/new.json
  def new
    @proyecto = Proyecto.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @proyecto }
    end
  end

  # GET /proyectos/1/edit
  def edit
    @proyecto = Proyecto.find(params[:id])
  end

  # POST /proyectos
  # POST /proyectos.json
  def create
    @proyecto = Proyecto.new(params[:proyecto])

    respond_to do |format|
      if @proyecto.save
        format.html { redirect_to @proyecto, notice: 'El proyecto fue creado.' }
        format.json { render json: @proyecto, status: :created, location: @proyecto }
      else
        format.html { render action: "new" }
        format.json { render json: @proyecto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /proyectos/1
  # PUT /proyectos/1.json
  def update
    @proyecto = Proyecto.find(params[:id])

    respond_to do |format|
      if @proyecto.update_attributes(params[:proyecto])
        format.html { redirect_to @proyecto, notice: 'El proyecto fue actualizado.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @proyecto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proyectos/1
  # DELETE /proyectos/1.json
  def destroy
    @proyecto = Proyecto.find(params[:id])
    @proyecto.destroy

    respond_to do |format|
      format.html { redirect_to proyectos_url }
      format.json { head :no_content }
    end
  end
	
	def fotos
		@proyecto = Proyecto.find(params[:id], :include => :fotos)
		
		respond_to do |format|
			format.html
			format.json{ head :no_content}
		end
	end
	
	def agregar_foto
		@proyecto = Proyecto.find(params[:id])
		@foto = Foto.new(:proyecto_id => @proyecto.id)
		
		respond_to do ||
				format.html
			format.json{ head :no_content}
		end
	end
	
	def ver_proyecto
		@proyecto = Proyecto.find(params[:id])
		render :layout => 'index'
	end
	
	def download

		proyecto = Proyecto.find(params[:id])
		fotos = Foto.find_all_by_proyecto_id(proyecto.id)
		videos = Video.find_all_by_proyecto_id(proyecto.id)
		discos = Disco.all
		#crear el directorio principal del proyecto y lo necesario
		FileUtils.mkdir "#{Rails.root}/public/downloads/proyecto"
		FileUtils.mkdir "#{Rails.root}/public/downloads/proyecto/javascript"
		FileUtils.mkdir "#{Rails.root}/public/downloads/proyecto/css"
		FileUtils.mkdir "#{Rails.root}/public/downloads/proyecto/images"
		FileUtils.mkdir "#{Rails.root}/public/downloads/proyecto/images/catalogo"
		FileUtils.mkdir "#{Rails.root}/public/downloads/proyecto/images/galeria"
		FileUtils.mkdir "#{Rails.root}/public/downloads/proyecto/video"
		FileUtils.mkdir "#{Rails.root}/public/downloads/proyecto/audio"
		#copio los archivos necesarios
		FileUtils.copy("#{Rails.root}/app/assets/stylesheets/glisse.css", "#{Rails.root}/public/downloads/proyecto/css/glisse.css")
		FileUtils.copy("#{Rails.root}/app/assets/javascripts/glisse.min.js", "#{Rails.root}/public/downloads/proyecto/javascript/glisse.min.js")
		FileUtils.copy("#{Rails.root}/app/assets/javascripts/audio-player.js", "#{Rails.root}/public/downloads/proyecto/javascript/audio-player.js")
		FileUtils.copy("#{Rails.root}/app/assets/images/presentacion/Mod_background.jpg", "#{Rails.root}/public/downloads/proyecto/images/Mod_background.jpg")
		FileUtils.copy("#{Rails.root}/app/assets/images/presentacion/portada.jpg", "#{Rails.root}/public/downloads/proyecto/images/portada.jpg")
		FileUtils.copy("#{Rails.root}/app/assets/images/presentacion/portada_catalogo.jpg", "#{Rails.root}/public/downloads/proyecto/images/portada_catalogo.jpg")
		FileUtils.copy("#{Rails.root}/app/assets/images/presentacion/portada_contacto.JPG", "#{Rails.root}/public/downloads/proyecto/images/portada_contacto.JPG")
		FileUtils.copy("#{Rails.root}/app/assets/images/presentacion/portada_fotos.JPG", "#{Rails.root}/public/downloads/proyecto/images/portada_fotos.JPG")
		FileUtils.copy("#{Rails.root}/app/assets/images/presentacion/portada_video.jpg", "#{Rails.root}/public/downloads/proyecto/images/portada_videos.jpg")
		FileUtils.copy("#{Rails.root}/app/assets/images/presentacion/favicon.ico", "#{Rails.root}/public/downloads/proyecto/images/favicon.ico")
		FileUtils.copy("#{Rails.root}/app/assets/images/presentacion/LOGO.ico", "#{Rails.root}/public/downloads/proyecto/images/LOGO.ico")
		FileUtils.copy("#{Rails.root}/public/jquery.min.js", "#{Rails.root}/public/downloads/proyecto/javascript/jquery.min.js")
		FileUtils.copy("#{Rails.root}/public/jwplayer.js", "#{Rails.root}/public/downloads/proyecto/javascript/jwplayer.min.js")
		FileUtils.copy("#{Rails.root}/public/player.swf", "#{Rails.root}/public/downloads/proyecto/javascript/player.swf")
		FileUtils.copy("#{Rails.root}/public/audio-player.swf", "#{Rails.root}/public/downloads/proyecto/javascript/audio-player.swf")
		
		discos.each do |disco|
			FileUtils.copy("#{Rails.root}/public/" + disco.imagen_url.to_s, "#{Rails.root}/public/downloads/proyecto/images/catalogo/" + disco.id.to_s + ".jpg")
			FileUtils.copy("#{Rails.root}/public/" + disco.muestra_url.to_s, "#{Rails.root}/public/downloads/proyecto/audio/" + disco.id.to_s + ".mp3")
		end
		
		fotos.each do |foto|
			FileUtils.copy("#{Rails.root}/public/" + foto.imagen_url.to_s, "#{Rails.root}/public/downloads/proyecto/images/galeria/" + foto.id.to_s + ".jpg")
			
			foto_string = "<img src='images/galeria/#{foto.id.to_s}.jpg' height = '200'/>"
		end
		
		videos.each do |video|
			FileUtils.copy("#{Rails.root}/public/" + video.video_url.to_s, "#{Rails.root}/public/downloads/proyecto/video/" + video.id.to_s + ".mp4")
		end

		#creo el index
		File.open("#{Rails.root}/public/downloads/proyecto/index.html", "w") do |f|
			f.puts '<!DOCTYPE html>
			<html>
			<head>
			<title>Presentacion del Disco</title>
			<link rel="shortcut icon" href="images/favicon.ico" />
			<script src="javascript/jquery.min.js"></script>
			<style>

      body{
	/*    background-color:#AFC4BD;*/
	background-image: url(images/Mod_background.jpg);
      }

      #container{
	background-image: url(images/Mod_background.jpg);
	background-repeat: no-repeat;
	background-position: center;

	height: 600px;
      }

      #content{
        text-align: center;
      }
    </style>
	</head>
	<body>
		<div id="container">
<div id="content">
  <img src="images/portada.jpg" usemap = "#links"  class = "imagen"  />
  <map id="links" name="links">
    <area shape="rect" coords="45, 36, 303, 304" href="galeria.html" alt="fotos" onmouseover="cambiarImagen(\'foto\')" onmouseout="volverPortada()"/>
    <area shape="rect" coords="305, 36, 564, 304" href="video.html " alt="video" onmouseover="cambiarImagen(\'video\')" onmouseout="volverPortada()"/>
    <area shape="rect" coords="45, 304, 303, 577" href="catalogo.html" alt="catalogo" onmouseover="cambiarImagen(\'catalogo\')" onmouseout="volverPortada()"/>
    <area shape="rect" coords="305, 304, 564, 577" href="contacto.html" alt="contacto" onmouseover="cambiarImagen(\'contacto\')" onmouseout="volverPortada()"/>
  </map>
</div>
		</div>
<script type="text/javascript">
  function cambiarImagen(imagen){
    if(imagen == "foto"){
      $(".imagen").attr("src","images/portada_fotos.JPG")
    }
    if(imagen == "video"){
      $(".imagen").attr("src","images/portada_videos.jpg" )
    }
    if(imagen == "catalogo"){
      $(".imagen").attr("src","images/portada_catalogo.jpg" )
    }
    if(imagen == "contacto"){
      $(".imagen").attr("src","images/portada_contacto.JPG" )
    }
  }
  
  function volverPortada(){
    $(".imagen").attr("src", "images/portada.jpg" )
  }
</script>
	</body>
	</html>'
		end		
		
		
		#internas
		head  = '<!DOCTYPE html><html><head><title>Presentacion del Disco</title>
						<link rel="shortcut icon" href="images/favicon.ico" />
						<script src="javascript/jquery.min.js"></script>
						<script src="javascript/glisse.min.js"></script>
						<script type="text/javascript" src="javascript/jwplayer.min.js"></script>
						<script type="text/javascript" src="javascript/audio-player.js"></script>
						<link rel="stylesheet" href="css/glisse.css" />
						<style>
							body{	background-image: url(images/Mod_background.jpg); }
							.container{ width: 681px; margin: 26px auto auto; border: 0.5px solid #97A29E; box-shadow: 4px 10px 5px #888; background-color: #FBFBFB; }
							.navbar{ width: 100%; float: left; padding-left: 10px;}
							.navbar ul{ float: right; background-color: #E87765; padding: 3px; padding-left: 10px; margin-right: 20px; }
							.navbar ul li{ list-style: none; float: left; margin-bottom: 5px; margin-right: 25px; 	color: #000000; font-family: Helvetica,serif; font-size: 0.7em; line-height: 1.6em; text-transform: uppercase; }\
							.navbar ul li a{ text-decoration: none; color: #333333; }
							hr{ background-color: #E87765; border-style: hidden; color: #E87765; height: 1px; }
							h3{ color: #A3A39E; font-family: Helvetica,serif; margin-left: 5px; }
							.content p, .content label, .content li, .footer p{ color: #424242; font-family: "Helvetica","Arial",sans-serif; font-size: 12px;}
							.footer p{ padding-left: 5px; }
							.footer p a{ text-decoration: none;}
						</style></head>
						<body><div class="container"><div class="navbar">
							<ul>
								<li><a href="index.html">Inicio</a></li>
								<li><a href="catalogo.html">Cat&aacute;logo</a></li>
								<li><a href="video.html">Video</a></li>

app/helpers/proyectos_helper.rb
module ProyectosHelper
end

app/views/proyectos/_form.html.erb
<%= form_for(@proyecto) do |f| %>
  <% if @proyecto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@proyecto.errors.count, "error") %> prohibited this proyecto from being saved:</h2>

      <ul>
      <% @proyecto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="actions">
    <%= f.submit%>
  </div>
<% end %>

app/views/proyectos/edit.html.erb
<h2>Editar Proyecto</h2>
<hr />

<p id="notice"><%= notice %></p>
<div style="margin-bottom: 20px;">
  <%= link_to content_tag(:i, '', :class => 'icon-arrow-left', :title => 'Volver a Proyectos'), proyectos_path  %>
  <%= link_to content_tag(:i, '', :class => 'icon-list-alt', :title => 'Ver'), @proyecto %> 
</div>

<%= render 'form' %>

app/views/proyectos/fotos.html.erb
<h2>Galeria de Imagenes</h2>
<hr />
<div>
  <%= link_to 'Agregar Imagen', :action => 'agregar_foto' %>
</div>
<% if @proyecto.fotos.present?  %>
  <%= render :partial => "fotos/tabla_proyecto_fotos" %>
<%  else %>
  <p>No tiene fotos ingresadas</p>
<% end  %>

app/views/proyectos/index.html.erb
<section>
  <div class="page-header">
    <h1>Proyectos<small> Lista de acciones</small></h1>
  </div>

  <table class="table table-striped table-bordered table-condensed">
    <thead>
    <th>Titulo</th>
    <th>Acciones</th>
    </thead>
    <% @proyectos.each do |proyecto| %>
      <tr>
	<td><%= proyecto.nombre %></td>
	<td>
	  <%= link_to content_tag(:i, '', :class => 'icon-play-circle', :title => 'Ver Demo'), ver_proyecto_path(:id => proyecto.id), :target => :blank %>
	  <%#= link_to content_tag(:i, '', :class => 'icon-download-alt', :title => 'Descargar Proyecto'), '#', :onclick => 'descarga()'%>
	  <%= link_to content_tag(:i, '', :class => 'icon-download-alt', :title => 'Descargar Proyecto'), :controller => 'proyectos', :action => 'download', :id => proyecto.id%>
	  <%= link_to content_tag(:i, '', :class => 'icon-picture', :title => 'Galeria'), index_fotos_path(:id => proyecto.id) %>
	  <%= link_to content_tag(:i, '', :class => 'icon-film', :title => 'Videos'), videos_path(:id => proyecto.id) %>
	  <%= link_to content_tag(:i, '', :class => 'icon-list-alt', :title => 'Ver'), proyecto %>
	  <%= link_to content_tag(:i, '', :class => 'icon-edit', :title => 'Editar'), edit_proyecto_path(proyecto)%>
	  <%= link_to content_tag(:i, '', :class => 'icon-ban-circle', :title => 'Eliminar'), proyecto, confirm: 'Esta seguro?', method: :delete %>
	</td>
      </tr>

    <% end %>
  </table>
  <%= link_to 'Agregar Proyecto', new_proyecto_path, :class => 'btn btn-primary' %>
</section>

<script type="text/javascript">
  function descarga(){
    window.location='<%= url_for :controller => 'proyectos',  :action=>"download" %>';
  }

</script>

app/views/proyectos/new.html.erb
<h2>Nuevo Proyecto</h2>
<hr />

<p id="notice"><%= notice %></p>
<div style="margin-bottom: 20px;">
  <%= link_to content_tag(:i, '', :class => 'icon-arrow-left', :title => 'Volver a Proyectos'), proyectos_path  %>
</div>

<%= render 'form' %>

app/views/proyectos/show.html.erb
<h2>Ver Proyecto</h2>
<hr />

<p id="notice"><%= notice %></p>
<div style="margin-bottom: 20px;">
  <%= link_to content_tag(:i, '', :class => 'icon-arrow-left', :title => 'Volver a Proyectos'), proyectos_path  %>
  <%= link_to content_tag(:i, '', :class => 'icon-edit', :title => 'Editar'), edit_proyecto_path(@proyecto) %> 
</div>

<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @proyecto.nombre %>
</p>

app/views/proyectos/ver_proyecto.html.erb
<div id="content">
  <%= image_tag "presentacion/portada.jpg", 'usemap' => '#links', :class => 'imagen' %>
  <map id="links" name="links">
    <area shape="rect" coords="45, 36, 303, 304" href="<%= ver_galeria_path%> " alt="fotos" onmouseover="cambiarImagen('foto')" onmouseout="volverPortada()"/>
    <area shape="rect" coords="305, 36, 564, 304" href="<%= ver_video_path%> " alt="video" onmouseover="cambiarImagen('video')" onmouseout="volverPortada()"/>
    <area shape="rect" coords="45, 304, 303, 577" href="<%= ver_catalogo_path%> " alt="catalogo" onmouseover="cambiarImagen('catalogo')" onmouseout="volverPortada()"/>
    <area shape="rect" coords="305, 304, 564, 577" href="# " alt="contacto" onmouseover="cambiarImagen('contacto')" onmouseout="volverPortada()"/>
  </map>
</div>

<script type="text/javascript">
  function cambiarImagen(imagen){
    if(imagen == 'foto'){
      $(".imagen").attr('src','<%= image_path('presentacion/portada_fotos.JPG') %>' )
    }
    if(imagen == 'video'){
      $(".imagen").attr('src','<%= image_path('presentacion/portada_video.jpg') %>' )
    }
    if(imagen == 'catalogo'){
      $(".imagen").attr('src','<%= image_path('presentacion/portada_catalogo.jpg') %>' )
    }
    if(imagen == 'contacto'){
      $(".imagen").attr('src','<%= image_path('presentacion/portada_contacto.JPG') %>' )
    }
  }
  
  function volverPortada(){
    $(".imagen").attr('src','<%= image_path('presentacion/portada.jpg') %>' )
  }
</script>