config/routes.rb
Forgpresentation::Application.routes.draw do

  resources :discos

  resources :proyectos
  resources :fotos
  resources :videos
  
  match '/:id/fotos', :to => 'fotos#index', :as => 'index_fotos'
  match '/fotos/:id', :to => 'fotos#show', :as => 'show_foto'
  match '/fotos/:id/edit', :to => 'fotos#edit', :as => 'edit_foto'
  match '/fotos/:id/new', :to => 'fotos#new', :as => 'new_foto'  
  match '/videos/:id/new', :to => 'videos#new', :as => 'new_video'  
  match '/proyectos/:id/ver_proyecto', :to => 'proyectos#ver_proyecto', :as => 'ver_proyecto'
  match '/videos/:id/ver_video', :to => 'videos#ver_video', :as => 'ver_video'
  match '/fotos/:id/ver_galeria', :to => 'fotos#ver_galeria', :as => 'ver_galeria'
  match '/discos/:id/ver_catalogo', :to => 'discos#ver_catalogo', :as => 'ver_catalogo'
  match 'download' => 'proyectos#download';
	

  root :to => 'proyectos#index'

end

app/models/video.rb
class Video < ActiveRecord::Base
		
	mount_uploader :video, VideoUploader
#	mount_uploader :video_mp4, AvatarUploader
	
	validates :nombre, :presence => true
	
	belongs_to :proyecto
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  # GET /videos
  # GET /videos.json
  def index
		#    @videos = Video.all
    @videos = Video.find_all_by_proyecto_id(params[:id])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @videos }
    end
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
    @video = Video.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @video }
    end
  end

  # GET /videos/new
  # GET /videos/new.json
  def new
    @video = Video.new
    @video.proyecto_id = params[:id]

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @video }
    end
  end

  # GET /videos/1/edit
  def edit
    @video = Video.find(params[:id])
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(params[:video])

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render json: @video, status: :created, location: @video }
      else
        format.html { render action: "new" }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /videos/1
  # PUT /videos/1.json
  def update
    @video = Video.find(params[:id])

    respond_to do |format|
      if @video.update_attributes(params[:video])
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video = Video.find(params[:id])
	proyecto_id = @video.proyecto_id
    @video.destroy

    respond_to do |format|
      format.html { redirect_to videos_path(:id =>proyecto_id ) }
      format.json { head :no_content }
    end
  end
	
	def ver_video
		@videos = Video.find_all_by_proyecto_id(params[:id])
		render :layout => "interna"
	end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<%= form_for @video, :html => { :multipart => true } do |f| %>
  <% if @video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
	<% @video.errors.full_messages.each do |msg| %>
	  <li><%= msg %></li>
	<% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :proyecto_id %><br />
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br />
    <%= f.text_area :descripcion %>
  </div>

  <div class="field">
    <%= f.label :video %>
    <%= f.file_field :video %>
  </div>

  <%#*<div class="field">%>
    <%#= f.label :video__mp4, 'Video mp4' %>
    <%#= f.file_field :video__mp4 %>
  <%#*</div>%>

  <%#*<span>%>
  <%#*MP4%>
  <%#*</span>%>
  <%#*<div class="field">%>
  <%#= f.file_field :video %>
  <%#*</div>%>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/videos/edit.html.erb
<h2>Editar Foto <small>Proyecto </small></h2>
<hr />

<div style="margin-bottom: 20px;">
  <%= link_to content_tag(:i, '', :class => 'icon-arrow-left', :title => 'Volver a Videos'), videos_path(:id => @video.proyecto_id) %> 
  <%= link_to content_tag(:i, '', :class => 'icon-list-alt', :title => 'Ver Video'), video_path(@video.id) %>
</div>

<%= render 'form' %>

app/views/videos/index.html.erb
<h2>Galeria de Videos <small>Proyecto </small></h2>
<hr />
<div style="margin-bottom: 20px;">
  <%= link_to content_tag(:i, '', :class => 'icon-arrow-left', :title => 'Volver a Proyectos'), proyectos_path %>  
  <%= link_to content_tag(:i, '', :class => 'icon-plus', :title => 'Agregar Video'), new_video_path(params[:id]) %>
</div>

<table class="table table-striped table-bordered table-condensed">
  <tr>
    <th>Nombre</th>
    <th>Descripcion</th>
    <th></th>

  </tr>

  <% @videos.each do |video| %>
    <tr>
      <td><%= video.nombre %></td>
      <td><%= video.descripcion %></td>
      <td>
	<%= link_to content_tag(:i, '', :class => 'icon-list-alt', :title => 'Ver Video'), video %>
	<%= link_to content_tag(:i, '', :class => 'icon-edit', :title => 'Editar Video'), edit_video_path(video) %>
	<%= link_to content_tag(:i, '', :class => 'icon-ban-circle', :title => 'Eliminar Video'), video, confirm: 'Esta seguro?', method: :delete %>
      </td>
    </tr>
  <% end %>
</table>

app/views/videos/new.html.erb
<h2>Nuevo Video <small>Proyecto </small></h2>
<hr />

<p id="notice"><%= notice %></p>
<div style="margin-bottom: 20px;">
  <%= link_to content_tag(:i, '', :class => 'icon-arrow-left', :title => 'Volver a Videos'), videos_path(:id => @video.proyecto_id) %> 
</div>

<%= render 'form' %>

app/views/videos/show.html.erb
<h2>Ver VIdeo <small>Proyecto </small></h2>
<hr />

<p id="notice"><%= notice %></p>
<div style="margin-bottom: 20px;">
  <%= link_to content_tag(:i, '', :class => 'icon-arrow-left', :title => 'Volver a Videos'), videos_path(:id => @video.proyecto_id)  %>
  <%= link_to content_tag(:i, '', :class => 'icon-edit', :title => 'Editar'), edit_video_path(@foto) %> 
</div>

<p>
  <b>Nombre:</b>
  <%= @video.nombre %>
</p>

<p>
  <b>Descripcion:</b>
  <%= @video.descripcion %>
</p>

<p>
  <b>Video:</b>
<%# browser = request.env['HTTP_USER_AGENT'] %>
<%# case browser %>
<%# when /Firefox/  then %>
<%#= video_tag(@video.video_url, :controls => true, :autobuffer => true) if @video.video?%>
<%# when /Chrome/  then %>
<%#= video_tag(@video.video_url, :controls => true, :autobuffer => true) if @video.video?%>
<%# when /Safari/  then %>
<%#= video_tag(@video.video_mp4_url, :controls => true, :autobuffer => true) if @video.video?%>
<%# end %>

<div id="prueba"></div>

<script type='text/javascript'>
  jwplayer("prueba").setup({
    flashplayer: "<%=  '../assets/player.swf' %>",
    file: '<%= @video.video_url %>'
  });
</script>

<%#= image_tag(@video.video_url)  if @video.video? %>
</p>

app/views/videos/ver_video.html.erb
<div>
  <div>
    <h3>Videos</h3>
    <hr />
  </div>
  <% @videos.each do |video| %>
    <div class="descripcion" style="margin-left: 10px;">
      <h4><%= video.nombre  %> </h4>
      <p><%= video.descripcion  %> </p>
    </div>
    <div style="text-align: center; padding-left: 136px;">
      <div id="video-<%= video.id %>"></div>
    </div>
    <script type='text/javascript'>
      jwplayer("video-<%= video.id %>").setup({
	flashplayer: "<%=  '../../assets/player.swf' %>",
	file: '<%= video.video_url %>'
      });
    </script>
  <% end %>
</div>