config/routes.rb
Forgpresentation::Application.routes.draw do

  resources :discos

  resources :proyectos
  resources :fotos
  resources :videos
  
  match '/:id/fotos', :to => 'fotos#index', :as => 'index_fotos'
  match '/fotos/:id', :to => 'fotos#show', :as => 'show_foto'
  match '/fotos/:id/edit', :to => 'fotos#edit', :as => 'edit_foto'
  match '/fotos/:id/new', :to => 'fotos#new', :as => 'new_foto'  
  match '/videos/:id/new', :to => 'videos#new', :as => 'new_video'  
  match '/proyectos/:id/ver_proyecto', :to => 'proyectos#ver_proyecto', :as => 'ver_proyecto'
  match '/videos/:id/ver_video', :to => 'videos#ver_video', :as => 'ver_video'
  match '/fotos/:id/ver_galeria', :to => 'fotos#ver_galeria', :as => 'ver_galeria'
  match '/discos/:id/ver_catalogo', :to => 'discos#ver_catalogo', :as => 'ver_catalogo'
  match 'download' => 'proyectos#download';
	

  root :to => 'proyectos#index'

end

app/models/foto.rb
class Foto < ActiveRecord::Base
	mount_uploader :imagen, AvatarUploader   
	
	validates :nombre, :presence => true
#	validates :tipo, :presence => true
	
	belongs_to :proyecto
end

app/controllers/fotos_controller.rb
class FotosController < ApplicationController
  # GET /fotos
  # GET /fotos.json
  def index
#    @fotos = Foto.all
    @fotos = Foto.find_all_by_proyecto_id(params[:id])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @fotos }
    end
  end

  # GET /fotos/1
  # GET /fotos/1.json
  def show
    @foto = Foto.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @foto }
    end
  end

  # GET /fotos/new
  # GET /fotos/new.json
  def new
    @foto = Foto.new
	@foto.proyecto_id = params[:id]

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @foto }
    end
  end

  # GET /fotos/1/edit
  def edit
    @foto = Foto.find(params[:id])
  end

  # POST /fotos
  # POST /fotos.json
  def create
    @foto = Foto.new(params[:foto])

    respond_to do |format|
      if @foto.save
        format.html { redirect_to index_fotos_path(:id => params[:foto][:proyecto_id]) , notice: 'Foto was successfully created.' }
        format.json { render json: @foto, status: :created, location: @foto }
      else
        format.html { render action: "new" }
        format.json { render json: @foto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /fotos/1
  # PUT /fotos/1.json
  def update
    @foto = Foto.find(params[:id])

    respond_to do |format|
      if @foto.update_attributes(params[:foto])
        format.html { redirect_to @foto, notice: 'Foto was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @foto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fotos/1
  # DELETE /fotos/1.json
  def destroy
    @foto = Foto.find(params[:id])
		id = @foto.proyecto_id
    @foto.destroy

    respond_to do |format|
      format.html { redirect_to index_fotos_path(:id => id) }
      format.json { head :no_content }
    end
  end
	
	def ver_galeria
		@fotos = Foto.find_all_by_proyecto_id(params[:id])
		 render :layout => "interna"
	end
end

app/helpers/fotos_helper.rb
module FotosHelper
end

app/views/fotos/_form.html.erb
<%= form_for @foto, :html => { :multipart => true } do |f| %>
  <% if @foto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@foto.errors.count, "error") %> prohibited this proyecto from being saved:</h2>

      <ul>
	<% @foto.errors.full_messages.each do |msg| %>
	  <li><%= msg %></li>
	<% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :proyecto_id %><br />
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>

  <div class="field">
    <%= f.label :descripcion %><br />
    <%= f.text_field :descripcion %>
  </div>

  <%#*<div class="field">%>
    <%#= f.label :tipo %><br />
    <%#= f.text_field :tipo %>
  <%#*</div>%>

  <div class="field">
    <%= f.label :imagen %><br />
    <%= f.file_field :imagen %>
  </div>

  <div class="actions">
    <%= f.submit%>
  </div>
<% end %>

app/views/fotos/edit.html.erb
<h2>Editar Foto <small>Proyecto </small></h2>
<hr />

<p id="notice"><%= notice %></p>
<div style="margin-bottom: 20px;">
  <%= link_to content_tag(:i, '', :class => 'icon-arrow-left', :title => 'Volver a Galeria'), index_fotos_path(@foto.proyecto_id) %> 
  <%= link_to content_tag(:i, '', :class => 'icon-list-alt', :title => 'Ver Foto'), show_foto_path(@foto.id)  %>
</div>

<%= render 'form' %>

app/views/fotos/index.html.erb
<h2>Galeria de Imagenes <small>Proyecto </small></h2>
<hr />
<div style="margin-bottom: 20px;">
  <%= link_to content_tag(:i, '', :class => 'icon-arrow-left', :title => 'Volver a Proyectos'), proyectos_path %>  
  <%= link_to content_tag(:i, '', :class => 'icon-plus', :title => 'Agregar Foto'), new_foto_path(params[:id]) %>
</div>
<%#= @fotos.inspect %>
<% if @fotos.present? %>  
  <div class="row">
    <%  @fotos.each do |foto| %>

      <div class="span3" style="text-align: center">
	<div>
	  <%#= image_tag foto.imagen.thumb('100x100').url if foto.imagen_uid %>
	  <%= image_tag foto.imagen_url if foto.imagen.present? %>
	</div>
	<div>
	  <%= foto.nombre %>
	  <div>
	    <%= link_to content_tag(:i, '', :class => 'icon-list-alt', :title => 'Ver' ), show_foto_path(foto.id) %>
	    <%= link_to content_tag(:i, '', :class => 'icon-edit', :title => 'Editar' ), edit_foto_path(foto.id) %>
	    <%= link_to content_tag(:i, '', :class => 'icon-ban-circle', :title => 'Eliminar' ), foto, confirm: 'Esta seguro?', method: :delete %>
	  </div>
	</div>
      </div>

    <% end %>
  </div>
<%  else %>
  <p>No tiene fotos ingresadas</p>
<% end  %>

app/views/fotos/new.html.erb
<h2>Nueva Foto <small>Proyecto </small></h2>
<hr />

<p id="notice"><%= notice %></p>
<div style="margin-bottom: 20px;">
  <%= link_to content_tag(:i, '', :class => 'icon-arrow-left', :title => 'Volver a Galeria'), index_fotos_path(@foto.proyecto_id) %> 
</div>
<%= render 'form' %>

app/views/fotos/show.html.erb
<h2>Ver Imagen <small>Proyecto </small></h2>
<hr />

<p id="notice"><%= notice %></p>
<div style="margin-bottom: 20px;">
  <%= link_to content_tag(:i, '', :class => 'icon-arrow-left', :title => 'Volver a Galeria'), index_fotos_path(:id => @foto.proyecto_id)  %>
  <%= link_to content_tag(:i, '', :class => 'icon-edit', :title => 'Editar'), edit_foto_path(@foto) %> 
</div>

<table>
  <tr>
    <td><b>Nombre:</b></td>
    <td><%= @foto.nombre %></td>
  </tr>

  <tr>

    <td><b>Descripcion:</b></td>
    <td><%= @foto.descripcion %></td>

  </tr>
  <tr>

    <td><b>Tipo:</b></td>
    <td><%= @foto.tipo %></td>
  </tr>
  <tr>

    <td><b>Imagen:</b></td>
    <td><%= image_tag @foto.imagen.thumb('200x200').url if @foto.imagen_uid%></td>

  </tr>
</table>

app/views/fotos/ver_galeria.html.erb
<div>
  <div>
    <h3>Galer&iacute;a de Im&aacute;genes</h3>
    <hr />
  </div>


  <% @fotos.each do |foto|%>
    <div style="margin: 10px; float:left">
      <%= image_tag foto.imagen_url, :height => '200', :class => 'pics' , "data-glisse-big" => foto.imagen.url, :rel => 'group', :title => foto.descripcion %>
      <div style="text-align: center;">
	<%= label_tag(foto.nombre) %>
      </div>
    </div>
  <% end %>
  <div style="clear: both"></div>
</div>
<script type="text/javascript">
  $(function(){
    $('.pics').glisse(
    {
      changeSpeed: 550,
      speed: 500,
      effect: 'bounce'
    })
  })
</script>

<style>
  #glisse-controls {
    position: fixed;
    bottom: 0;
    left: 0;
    right: 0;
    height: 40px;
    font-size: 13px;
    font-weight: bold;
    color: #fff;
    border-top: 1px solid #2d2f35;
    text-shadow: 0 -1px 0 #333333;
    background-image: -webkit-gradient(linear, 50% 0%, 50% 100%, color-stop(0%, rgba(87, 90, 98, 0.9)), color-stop(100%, rgba(62, 65, 72, 0.9)));
    background-image: -webkit-linear-gradient(rgba(87, 90, 98, 0.9), rgba(62, 65, 72, 0.9));
    background-image: -moz-linear-gradient(rgba(87, 90, 98, 0.9), rgba(62, 65, 72, 0.9));
    background-image: -o-linear-gradient(rgba(87, 90, 98, 0.9), rgba(62, 65, 72, 0.9));
    background-image: -ms-linear-gradient(rgba(87, 90, 98, 0.9), rgba(62, 65, 72, 0.9));
    background-image: linear-gradient(rgba(87, 90, 98, 0.9), rgba(62, 65, 72, 0.9));
    -moz-box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.15), 0 1px 3px rgba(0, 0, 0, 0.7);
    -webkit-box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.15), 0 1px 3px rgba(0, 0, 0, 0.7);
    -o-box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.15), 0 1px 3px rgba(0, 0, 0, 0.7);
    box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.15), 0 1px 3px rgba(0, 0, 0, 0.7); }

  .glisse-next a, .glisse-prev a {
    position: absolute;
    display: block;
    left: 0;
    height: 39px;
    width: 39px;
    font-family: 'WebSymbolsRegular';
    line-height: 40px;
    color: white;
    font-size: 16px;
    text-align: center;
    text-decoration: none;
    text-shadow: 0 -1px 0 black; }

  .glisse-next a:active, .glisse-prev a:active {
    text-shadow: 0 0 30px white, 0 0 10px white; }

  .glisse-prev a {
    border-right: 1px solid #2d2f35;
    -moz-box-shadow: inset -1px 0 0 rgba(255, 255, 255, 0.15);
    -webkit-box-shadow: inset -1px 0 0 rgba(255, 255, 255, 0.15);
    -o-box-shadow: inset -1px 0 0 rgba(255, 255, 255, 0.15);
    box-shadow: inset -1px 0 0 rgba(255, 255, 255, 0.15); }

  .glisse-next a {
    left: auto;
    right: 0;
    border-left: 1px solid #2d2f35;
    -moz-box-shadow: inset 1px 0 0 rgba(255, 255, 255, 0.15);
    -webkit-box-shadow: inset 1px 0 0 rgba(255, 255, 255, 0.15);
    -o-box-shadow: inset 1px 0 0 rgba(255, 255, 255, 0.15);
    box-shadow: inset 1px 0 0 rgba(255, 255, 255, 0.15); }

  .glisse-legend {
    text-overflow: ellipsis;
    overflow: hidden;
    white-space: nowrap;
    position: absolute;
    top: 0;
    bottom: 0;
    left: 40px;
    right: 40px;
    text-align: center;
    line-height: 40px; }
</style>