config/routes.rb
Forgpresentation::Application.routes.draw do

  resources :discos

  resources :proyectos
  resources :fotos
  resources :videos
  
  match '/:id/fotos', :to => 'fotos#index', :as => 'index_fotos'
  match '/fotos/:id', :to => 'fotos#show', :as => 'show_foto'
  match '/fotos/:id/edit', :to => 'fotos#edit', :as => 'edit_foto'
  match '/fotos/:id/new', :to => 'fotos#new', :as => 'new_foto'  
  match '/videos/:id/new', :to => 'videos#new', :as => 'new_video'  
  match '/proyectos/:id/ver_proyecto', :to => 'proyectos#ver_proyecto', :as => 'ver_proyecto'
  match '/videos/:id/ver_video', :to => 'videos#ver_video', :as => 'ver_video'
  match '/fotos/:id/ver_galeria', :to => 'fotos#ver_galeria', :as => 'ver_galeria'
  match '/discos/:id/ver_catalogo', :to => 'discos#ver_catalogo', :as => 'ver_catalogo'
  match 'download' => 'proyectos#download';
	

  root :to => 'proyectos#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Bootstrap, from Twitter</title>
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le styles -->

    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="images/favicon.ico">
    <link rel="apple-touch-icon" href="images/apple-touch-icon.png">
    <link rel="apple-touch-icon" sizes="72x72" href="images/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="114x114" href="images/apple-touch-icon-114x114.png">
    <title>Forgpresentation</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  </head>

  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Presentaciones</a>
          <div class="nav-collapse">
            <ul class="nav">
              <li><%= link_to "Proyectos", proyectos_path %></li>
              <li><%= link_to "Catalogo", discos_path%></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">

      <%= yield %>

    </div> <!-- /container -->

  </body>
</html>

app/views/layouts/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Presentacion del Disco</title>
    <%= javascript_include_tag 'application' %>
    <style>

      body{
	/*    background-color:#AFC4BD;*/
	background-image: url(/assets/presentacion/Mod_background.jpg);
      }

      #container{
	/*    background-color:#AFC4BD;*/
	background-image: url(/assets/presentacion/Mod_background.jpg);
	/*    background-image: url(/assets/presentacion/portada_fotos.JPG);*/
	background-repeat: no-repeat;
	background-position: center;

	height: 600px;
      }

      #content{
        text-align: center;
      }
    </style>
  </head>
  <body>
    <div id="container">
      <%= yield  %>
    </div>
  </body>
</html>

app/views/layouts/interna.html.erb
<!--?xml version="1.0" encoding="UTF-8"?-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

    <meta name="Generator" content="iWeb 3.0" />
    <meta name="iWeb-Build" content="local-build-20120225" />
    <meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7" />
    <meta name="viewport" content="width=684" />

    <title>Presentacion del Disco</title>
    <%= stylesheet_link_tag    "glisse", :media => "all" %>
    <%= stylesheet_link_tag    "interna", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "glisse.min" %>
    <style>

<%#*body{ background-color:#AFC4BD}%>
      body{
	background-image: url(/assets/presentacion/Mod_background.jpg);
      }
      .container{
	width: 681px;
	margin: 26px auto auto;
	border: 0.5px solid #97A29E;
	box-shadow: 4px 10px 5px #888;
	background-color: #FBFBFB;
      }

      .navbar{
	width: 100%;
	float: left;
	padding-left: 10px;
      }

      .navbar ul{
	float: right;
	background-color: #E87765;
	padding: 3px;
	padding-left: 10px;
	margin-right: 20px;
      }

      .navbar ul li{
	list-style: none;
	float: left;
	margin-bottom: 5px;
	margin-right: 25px;

	color: #000000;
	font-family: Helvetica,serif;
	font-size: 0.7em;
	line-height: 1.6em;
	text-transform: uppercase;
      }

      .navbar ul li a{
	text-decoration: none;
	color: #333333;
      }

      hr{
	background-color: #E87765;
	border-style: hidden;
	color: #E87765;
	height: 1px;
      }

      h3{
	color: #A3A39E;
	font-family: Helvetica,serif;
	margin-left: 5px;
      }

      .content p, .content label, .content li, .footer p{
	color: #424242;
	font-family: 'Helvetica','Arial',sans-serif;
	font-size: 12px;
      }

      .footer p{
	padding-left: 5px;
      }

      .footer p a{
	text-decoration: none;
      }
    </style>
  </head>
  <body>
    <div class="container">
      <div class="navbar">
	<ul>
	  <li><%= link_to 'Inicio', ver_proyecto_path(:id => params[:id]) %></li>
	  <li><%= link_to 'Catalogo', ver_catalogo_path %></li>
	  <li><%= link_to 'Video', ver_video_path(:id => params[:id]) %></li>
	  <li><%= link_to 'Galeria', ver_galeria_path(:id => params[:id]) %></li>
	</ul>
      </div>
      <div class="content">
	<%= yield %>
      </div>
      <div class="footer">
	<hr />
	<p>Para contactar con Germán Lema, <a title="Envia email" href=" mailto:gerlema@gmail.com">aqu&iacute;</a></p>
      </div>
    </div>

  </body>
</html>